name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - obs-pages
    paths: 
      - 'README.md'
      - 'overrides/**'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    uses: ObsidianPublisher/actions/.github/workflows/deploy.yml@obs-pages
    secrets:
      GH_PAT: ${{ secrets.GITHUB_TOKEN }}